version: '3'

services:
  rails-puma-db:
    container_name: 'rails-puma-db'
    image: postgres:11.7-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5433:5432'

# rails 6.0.3.2
# DOCKER_UID=$(id -u $USER) DOCKER_GID=$(id -g $USER) docker-compose up
  rails-puma-web:
    container_name: 'rails-puma-web'
    user: $DOCKER_UID:$DOCKER_GID
    build:
      context: .
      args:
        UID: $DOCKER_UID
        GID: $DOCKER_GID
    tty: true
    stdin_open: true
    volumes:
      - .:/workspace/myapp:cached
    depends_on:
      - rails-puma-db
    ports:
      - '3000:3000'
    environment:
      RAILS_ENV: development