development:
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: postgres
  password: postgres
  host: rails-rswag-db
  database: rails_rswag_development

test:
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: postgres
  password: postgres
  host: rails-rswag-db
  database: rails_rswag_test