development:
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: postgres
  password: postgres
  host: rails-puma-db
  database: rails_puma_development

test:
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: postgres
  password: postgres
  host: rails-puma-db
  database: rails_puma_test