# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.synced_folder '.', '/vagrant', disabled: true
  
  config.vm.provider "virtualbox" do |v|
    v.name = "centos_7_docker-compose"
  end

  config.vm.network :forwarded_port, host: 2231, guest: 22
  config.vm.network "private_network", ip: "192.168.33.21"

  # Run scripts for all VMs  
  config.vm.provision :shell, path: 'scripts/set_docker_compose.sh'
end
